# Generated by Django 5.2.3 on 2025-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medicine_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='title',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
