# Generated by Django 5.2.3 on 2025-07-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_document_user_alter_document_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='documents',
        ),
    ]
