services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - postgres
    links:
      - "postgres:database"
      - "postgres:db"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: npm run start
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - "postgres:database"
      - "postgres:db"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rag:
    build: ./rag
    container_name: rag
    ports:
      - "8008:8008"
    volumes:
      - rag_data:/app/data
    environment:
      - DEBUG=True
    depends_on:
      - postgres

volumes:
  postgres_data:
  rag_data: